trigger:
  branches:
    include:
    - main
  paths:
    include:
    - aks-cluster/aks-cluster-iac

pool:
  name: 'Azure Pipelines'

stages:

- stage: Validate
  displayName: 'QA Code'
  jobs:
  - job: Linter
    displayName: 'Linter Test'
    steps:
    - task: Bash@3
      displayName: Show Directory Contents
      inputs:
        targetType: 'inline'
        script: |
          echo "1 current directory $(pwd)"
          tree "$(System.DefaultWorkingDirectory)"
    - task: Bash@3
      displayName: 'Validate Terraform Code'
      inputs:
        targetType: 'inline'
        script: |
          echo "2 current directory is $(pwd)"
          cd $(System.DefaultWorkingDirectory)/aks-cluster/aks-cluster-iac
          echo "3 current directory is $(pwd)"
          ls -la
          ls -la ../
          terraform init
          terraform validate
          pwd

- stage: Plan
  jobs:
  - job: Speculative
    displayName: 'Run Speculative Plan'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          pwd
          cd aks-cluster/aks-cluster-iac
          terraform init
          terraform plan

- stage: Apply
  jobs:
  - job: Deploy
    displayName: 'Deploy Infrastructure'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          pwd
          cd aks-cluster/aks-cluster-iac
          terraform init
          terraform apply -auto-approve